name: Release Build

on:
  push:
    tags: v*

jobs:
  release-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3
        
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: zulu
          cache: maven

      - name: Build with Maven
        run: mvn -B test dependency:copy-dependencies --file pom.xml

      - name: Create Release File
        run: zip -r ${artifactId}.zip ./${artifactId}.bat ./target

      - name: Create Github Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${artifactId}.zip
